### PR TITLE
add:Upload pack program

### PR DESCRIPTION
**Pull request by WXZing**
Using Nuitka & Python 3.11 to pack.

### CODE REVIEW

**Review by DuckDuckStudio — CHANGES_REQUESTED** [review]
tag?

**Comment by WXZing** [comment]
Err…… v1.9 ？

**Review by DuckDuckStudio — APPROVED** [review]
Ok, I Approve the change and set tag v1.9.

**Comment by DuckDuckStudio** [comment]
The change will Merge.

**Pull request merged**
